<a href="https://colab.research.google.com/github/stefvas/neural-networks/blob/main/ergasia1_UCI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Το dataset περιλαμβάνει data που συγκέντρωσε το MAGIC Telescope. Συγκεκριμένα, το τηλεσκόπιο τράβηξε δεκάδες χιλιάδες φωτογραφίες από electromagnetic showers στην ατμόσφαιρα. Αναλύοντας τις 10 παραμέτρους των shower images που προκύπτουν από το τηλεσκόπιο, κατηγοριοποιούμε τα showers σε εκείνα που προκλήθηκαν από gamma rays (g) και σε hadronic showers (h), δηλαδή σε εκείνα που προκλήθηκαν από τις κοσμικές ακτίνες της ατμόσφαιρας

In [3]:
import pandas as pd
df = pd.read_csv("magic04.data", header=None)
df

0         1       2       3   ...       7        8         9   10
0       28.7967   16.0021  2.6449  0.3918  ...  -8.2027  40.0920   81.8828   g
1       31.6036   11.7235  2.5185  0.5303  ...  -9.9574   6.3609  205.2610   g
2      162.0520  136.0310  4.0612  0.0374  ... -45.2160  76.9600  256.7880   g
3       23.8172    9.5728  2.3385  0.6147  ...  -7.1513  10.4490  116.7370   g
4       75.1362   30.9205  3.1611  0.3168  ...  21.8393   4.6480  356.4620   g
...         ...       ...     ...     ...  ...      ...      ...       ...  ..
19015   21.3846   10.9170  2.6161  0.5857  ...   2.8766   2.4229  106.8258   h
19016   28.9452    6.7020  2.2672  0.5351  ...  -2.9632  86.7975  247.4560   h
19017   75.4455   47.5305  3.4483  0.1417  ...  -9.4662  30.2987  256.5166   h
19018  120.5135   76.9018  3.9939  0.0944  ... -63.8389  84.6874  408.3166   h
19019  187.1814   53.0014  3.2093  0.2876  ...  31.4755  52.7310  272.3174   h

[19020 rows x 11 columns]

Δεν κάναμε κάποια μετατροπή στο dataset πρωτού το ανεβάσαμε. Επίσης διαβάσαμε στην περιγραφή ότι δεν περιλαμβάνει κενές τιμές.

Eπαλήθευση:

In [4]:
df.isnull().values.any()

False

In [5]:
df

0         1       2       3   ...       7        8         9   10
0       28.7967   16.0021  2.6449  0.3918  ...  -8.2027  40.0920   81.8828   g
1       31.6036   11.7235  2.5185  0.5303  ...  -9.9574   6.3609  205.2610   g
2      162.0520  136.0310  4.0612  0.0374  ... -45.2160  76.9600  256.7880   g
3       23.8172    9.5728  2.3385  0.6147  ...  -7.1513  10.4490  116.7370   g
4       75.1362   30.9205  3.1611  0.3168  ...  21.8393   4.6480  356.4620   g
...         ...       ...     ...     ...  ...      ...      ...       ...  ..
19015   21.3846   10.9170  2.6161  0.5857  ...   2.8766   2.4229  106.8258   h
19016   28.9452    6.7020  2.2672  0.5351  ...  -2.9632  86.7975  247.4560   h
19017   75.4455   47.5305  3.4483  0.1417  ...  -9.4662  30.2987  256.5166   h
19018  120.5135   76.9018  3.9939  0.0944  ... -63.8389  84.6874  408.3166   h
19019  187.1814   53.0014  3.2093  0.2876  ...  31.4755  52.7310  272.3174   h

[19020 rows x 11 columns]

χωρίζουμε τα data : features (x) , labels (y)

In [6]:
featueres_df=df.loc[:,0:9]
labels_df=df.loc[:,10:10]
print(featueres_df.shape)
print(labels_df.shape)

(19020, 10)
(19020, 1)


παρουσιάζονται καλύτερα ως numpy arrays:

In [7]:
import numpy as np


*  features: nympy array of 19020 rows and 10 columns
*  total of 190200 samples

In [8]:
features=featueres_df.values
print(features)
print(features.shape)

[[ 28.7967  16.0021   2.6449 ...  -8.2027  40.092   81.8828]
 [ 31.6036  11.7235   2.5185 ...  -9.9574   6.3609 205.261 ]
 [162.052  136.031    4.0612 ... -45.216   76.96   256.788 ]
 ...
 [ 75.4455  47.5305   3.4483 ...  -9.4662  30.2987 256.5166]
 [120.5135  76.9018   3.9939 ... -63.8389  84.6874 408.3166]
 [187.1814  53.0014   3.2093 ...  31.4755  52.731  272.3174]]
(19020, 10)


Labels: numpy array of 19020 rows and 1 column


In [9]:
labels=labels_df.values.reshape(19020,)
print(labels)
print(labels.shape)

['g' 'g' 'g' ... 'h' 'h' 'h']
(19020,)


Ο τύπος των δεδομένων στα features είναι float:

In [10]:
print(type(features[0,0]))

<class 'numpy.float64'>


Ο τύπος των δεδομένων στα labels είναι string:

In [11]:
print(type(labels[0]))

<class 'str'>


* Oι κλάσεις βρίσκονται στην τελευταία στήλη και διακρίνονται σε "gamma" : "g" και "hadron" : "h".
* Δεν έχουμε επικεφαλίδες ούτε αρίθμηση γραμμών
* Δεν απουσιάζει κανένα δείγμα






Έλεγχος αν το dataset είναι balanced:

In [12]:
print("number of classes: ",len(labels))
g=0
for i in range(len(labels)):
  if labels[i]=="g":
    g=g+1

h=len(labels)-g
print("number of g: ",g,", number of h: ",h)
perc=min(g,h)/len(labels)
if perc<0.4:
  print("Not balanced. Percentage = ",perc)
else:
  print("Balanced. Percentage = ",perc)


number of classes:  19020
number of g:  12332 , number of h:  6688
Not balanced. Percentage =  0.3516298633017876


Διαχωρίζουμε το σύνολο δεδομένων σε σύνολο εκπαίδευσης (train set) και σύνολο (test set) με 30% των δειγμάτων στο test set

In [14]:
from sklearn.model_selection import train_test_split
features_train,features_test,labels_train,labels_test=train_test_split(features,labels,test_size=0.3)

In [18]:
from sklearn.dummy import DummyClassifier
dc_uniform = DummyClassifier(strategy="uniform")
dc_constant_g = DummyClassifier(strategy="constant", constant='g')
dc_constant_h = DummyClassifier(strategy="constant", constant='h')
dc_most_frequent = DummyClassifier(strategy="most_frequent")
dc_stratified = DummyClassifier(strategy="stratified")

In [20]:
magic_accuracy = {}
dc_uniform.fit(features_train, labels_train)
magic_accuracy['uniform (random)'] = dc_uniform.score(features_train, labels_train)
model = dc_constant_g.fit(features_train, labels_train)
magic_accuracy['constant g'] = dc_constant_g.score(features_train, labels_train)
model = dc_constant_h.fit(features_train, labels_train)
magic_accuracy['constant h'] = dc_constant_h.score(features_train, labels_train)
model = dc_most_frequent.fit(features_train, labels_train)
magic_accuracy['most frequent label'] = dc_most_frequent.score(features_train, labels_train)
model = dc_stratified.fit(features_train, labels_train)
magic_accuracy['stratified'] = dc_stratified.score(features_train, labels_train)


In [21]:
print("Classification Accuracy on the magic Dataset (30% test set)\n")
sorted_accuracy = [(k, magic_accuracy[k]) for k in sorted(magic_accuracy, key=magic_accuracy.get, reverse=True)]
for k, v in sorted_accuracy:
  print(k,v)

Classification Accuracy on the magic Dataset (30% test set)

constant g 0.6499924891092084
most frequent label 0.6499924891092084
stratified 0.5469430674477993
uniform (random) 0.5000751089079165
constant h 0.35000751089079163


In [22]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
model = gnb.fit(features_train, labels_train)
magic_accuracy['gaussian naive bayes'] = gnb.score(features_train, labels_train)
print("Classification Accuracy on the magic Dataset (30% test set)\n")
sorted_accuracy = [(k, magic_accuracy[k]) for k in sorted(magic_accuracy, key=magic_accuracy.get, reverse=True)]
for k, v in sorted_accuracy:
  print(k,v)

Classification Accuracy on the magic Dataset (30% test set)

gaussian naive bayes 0.7238996544990236
constant g 0.6499924891092084
most frequent label 0.6499924891092084
stratified 0.5469430674477993
uniform (random) 0.5000751089079165
constant h 0.35000751089079163
